default_agent = "auto-approve"
bypass_tool_permissions = true

[tools.bash]
allowlist = [
    "basename",
    "cat",
    "cd",
    "comm",
    "cut",
    "date",
    "diff",
    "dirname",
    "du",
    "echo",
    "file",
    "find",
    "fmt",
    "fold",
    "git add",
    "git branch",
    "git commit",
    "git diff",
    "git log",
    "git ls-files",
    "git show",
    "git status",
    "grep",
    "head",
    "join",
    "less",
    "ls",
    "md5sum",
    "mkdir",
    "more",
    "nl",
    "od",
    "paste",
    "pwd",
    "readlink",
    "sha1sum",
    "sha256sum",
    "shasum",
    "sort",
    "stat",
    "sum",
    "tac",
    "tail",
    "tr",
    "tree",
    "uname",
    "uniq",
    "wc",
    "which",
    "whoami",
]
